#!/bin/sh

PWFILE=$HOME/Dropbox/passwd.gpg
what="$1"
echo -n "Password: "
stty -echo
read password
stty echo


(
    gpg --decrypt "$PWFILE"
    echo "$what: $password"
) | gpg --encrypt-to=jamie@jamieiles.com --encrypt --armor | sponge "$PWFILE"
